### ISSUE TITLE
Crash on 1.12.0.28

### ISSUE THREAD

**Issue by rfsousa** [minecraft-linux/mcpelauncher-server#5]
mcpelauncher-server crashes on 1.12.0.28. Here's the log,

16:01:55 Trace [HybrisUtils] Loaded OS library libm.so.6
16:01:55 Trace [HybrisUtils] Loaded OS library libz.so.1
16:01:55 Trace [Launcher] Loading Minecraft library
16:02:07 Info  [Launcher] Loaded Minecraft library
16:02:07 Debug [Launcher] Minecraft is at offset 0xb0a1c000
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
16:02:07 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
16:02:07 Info  [Launcher] Game version: 1.12.0
16:02:07 Info  [Launcher] Applying patches
16:02:07 Trace [Patch] Patching - original: 85 83 87 86 131
16:02:07 Trace [Patch] Patching - result: 233 5 125 101 76
16:02:07 Trace [Launcher] Initializing AppPlatform (vtable)
16:02:07 Trace [AppPlatform] Vtable size = 265
16:02:07 Trace [Launcher] Initializing AppPlatform (create instance)
16:02:07 Trace [Launcher] Initializing AppPlatform (initialize call)
16:02:07 Trace [AppPlatform] createDeviceID (from file): 6cbfbd55-a39d-46eb-944a-37d135e3d7fb
16:02:07 Trace [Launcher] Loading server properties
16:02:07 Trace [Launcher] Loading whitelist and operator list
16:02:07 Trace [Launcher] Setting up level settings
16:02:07 Trace [Launcher] Initializing FilePathManager
Signal 11 received
Backtrace elements: 2
#0 ./mcpelauncher-server(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x55b9bd]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xb7f79d4c]
Dumping stack...
#12 HYBRIS (null)+-1242827186 in libminecraftpe.so+0x54a364e [0xb5ebf64e]
#13 HYBRIS (null)+-1331576832 in libminecraftpe.so+0x0000 [0xb0a1c000]
#26 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#27 HYBRIS (null)+-1242990325 in libminecraftpe.so+0x547b90b [0xb5e9790b]
#28 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#29 HYBRIS (null)+-1214134304 in libminecraftpe.so+0x70007e0 [0xb7a1c7e0]
#30 HYBRIS (null)+-1214134304 in libminecraftpe.so+0x70007e0 [0xb7a1c7e0]
#33 HYBRIS (null)+-1214134304 in libminecraftpe.so+0x70007e0 [0xb7a1c7e0]
#40 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<unsigned char const, std::string>, false, false>, bool> std::_Hashtable<unsigned char, std::pair<unsigned char const, std::string>, std::allocator<std::pair<unsigned char const, std::string> >, std::__detail::_Select1st, std::equal_to<unsigned char>, std::hash<unsigned char>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_insert<std::pair<unsigned char const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<unsigned char const, std::string>, false> > > >(std::pair<unsigned char const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<unsigned char const, std::string>, false> > > const&, std::integral_constant<bool, true>)+12 in libminecraftpe.so+0x3d1732c [0xb473332c]
#156 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#159 HYBRIS (null)+-1275469456 in libminecraftpe.so+0x3582170 [0xb3f9e170]
#160 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x54289cc [0xb5e449cc]
#163 HYBRIS (null)+-1275470944 in libminecraftpe.so+0x3581ba0 [0xb3f9dba0]
#166 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x54289b6 [0xb5e449b6]
#167 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#168 HYBRIS (null)+-1275469393 in libminecraftpe.so+0x35821af [0xb3f9e1af]
#170 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x54289b6 [0xb5e449b6]
#171 HYBRIS (null)+-1242982503 in libminecraftpe.so+0x547d799 [0xb5e99799]
#175 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#176 HYBRIS GameRules::_registerRules()+7473 in libminecraftpe.so+0x357d951 [0xb3f99951]
#180 HYBRIS GameRules::_registerRules()+15 in libminecraftpe.so+0x357bc2f [0xb3f97c2f]
#181 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#184 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x54289b6 [0xb5e449b6]
#188 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x54289b6 [0xb5e449b6]
#189 HYBRIS (null)+-1243179977 in libminecraftpe.so+0x544d437 [0xb5e69437]
#192 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#201 HYBRIS (null)+-1243302655 in libminecraftpe.so+0x542f501 [0xb5e4b501]
#202 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#204 HYBRIS PermissionsFile::readPermissionFile()+545 in libminecraftpe.so+0x2bce931 [0xb35ea931]
#228 HYBRIS __cxxabiv1::__vmi_class_type_info::__do_dyncast(int, __cxxabiv1::__class_type_info::__sub_kind, __cxxabiv1::__class_type_info const*, void const*, __cxxabiv1::__class_type_info const*, void const*, __cxxabiv1::__class_type_info::__dyncast_result&) const+1107 in libminecraftpe.so+0x542b8b3 [0xb5e478b3]
#229 HYBRIS (null)+-1238837503 in libminecraftpe.so+0x5871701 [0xb628d701]
#230 HYBRIS (null)+-1238835348 in libminecraftpe.so+0x5871f6c [0xb628df6c]
#248 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#250 HYBRIS std::vector<GameRule, std::allocator<GameRule> >::resize(unsigned int)+12 in libminecraftpe.so+0x3580b1c [0xb3f9cb1c]
#258 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x54289b6 [0xb5e449b6]
#260 HYBRIS (null)+-1267816177 in libminecraftpe.so+0x3cce90f [0xb46ea90f]
#262 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#300 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#378 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#394 HYBRIS (null)+-1216699320 in libminecraftpe.so+0x6d8e448 [0xb77aa448]
#400 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x542aca7 [0xb5e46ca7]
#426 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x54289b6 [0xb5e449b6]
#490 HYBRIS Level::_checkUserStorage()+0 in libminecraftpe.so+0x34c5b80 [0xb3ee1b80]
#919 HYBRIS (null)+-1224670976 in libminecraftpe.so+0x65f4100 [0xb7010100]

**Comment by jmiahman** [comment]
Seeing the same thing..

08:35:24 Trace [HybrisUtils] Loaded OS library libm.so.6
08:35:24 Trace [HybrisUtils] Loaded OS library libz.so.1
08:35:24 Trace [Launcher] Loading Minecraft library
08:35:35 Info  [Launcher] Loaded Minecraft library
08:35:35 Debug [Launcher] Minecraft is at offset 0xf097c000
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
08:35:35 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
08:35:35 Info  [Launcher] Game version: 1.12.0
08:35:35 Info  [Launcher] Applying patches
08:35:35 Trace [Patch] Patching - original: 85 83 87 86 131
08:35:35 Trace [Patch] Patching - result: 233 65 27 40 20
08:35:35 Trace [Launcher] Initializing AppPlatform (vtable)
08:35:35 Trace [AppPlatform] Vtable size = 265
08:35:35 Trace [Launcher] Initializing AppPlatform (create instance)
08:35:35 Trace [Launcher] Initializing AppPlatform (initialize call)
08:35:35 Trace [AppPlatform] createDeviceID (from file): 4a99916f-27fe-4bbe-aecb-1fc3eaf08171
08:35:35 Trace [Launcher] Loading server properties
08:35:35 Trace [Launcher] Loading whitelist and operator list
08:35:35 Trace [Launcher] Setting up level settings
08:35:35 Trace [Launcher] Initializing FilePathManager
Signal 11 received
Backtrace elements: 2
#0 mcpelauncher-server(_ZN12CrashHandler12handleSignalEiPv+0x9d) [0x80de277]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f0f960]
Dumping stack...
#66 HYBRIS (null)+-169740722 in libminecraftpe.so+0x54a364e [0xf5e1f64e]
#76 HYBRIS Core::FileStorageArea::sStorageAreaFileStats+8 in libminecraftpe.so+0x6fbe5d4 [0xf793a5d4]
#77 HYBRIS (null)+-169903861 in libminecraftpe.so+0x547b90b [0xf5df790b]
#78 HYBRIS (null)+-143612856 in libminecraftpe.so+0x6d8e448 [0xf770a448]
#79 HYBRIS (null)+-141047840 in libminecraftpe.so+0x70007e0 [0xf797c7e0]
#80 HYBRIS (null)+-141047840 in libminecraftpe.so+0x70007e0 [0xf797c7e0]
#83 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x3d14720 [0xf4690720]
#90 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<unsigned char const, std::string>, false, false>, bool> std::_Hashtable<unsigned char, std::pair<unsigned char const, std::string>, std::allocator<std::pair<unsigned char const, std::string> >, std::__detail::_Select1st, std::equal_to<unsigned char>, std::hash<unsigned char>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_insert<std::pair<unsigned char const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<unsigned char const, std::string>, false> > > >(std::pair<unsigned char const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<unsigned char const, std::string>, false> > > const&, std::integral_constant<bool, true>)+12 in libminecraftpe.so+0x3d1732c [0xf469332c]
#92 HYBRIS (null)+-143612856 in libminecraftpe.so+0x6d8e448 [0xf770a448]
#93 HYBRIS (null)+-141047840 in libminecraftpe.so+0x70007e0 [0xf797c7e0]
#95 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x3d14720 [0xf4690720]
#96 HYBRIS (null)+-141047840 in libminecraftpe.so+0x70007e0 [0xf797c7e0]
#97 HYBRIS (null)+-143216640 in libminecraftpe.so+0x6def000 [0xf776b000]
#100 HYBRIS (null)+-143612856 in libminecraftpe.so+0x6d8e448 [0xf770a448]
#102 HYBRIS (null)+-236400808 in libminecraftpe.so+0x1510f58 [0xf1e8cf58]
#103 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x3d14720 [0xf4690720]
#104 HYBRIS (null)+-141047840 in libminecraftpe.so+0x70007e0 [0xf797c7e0]
#186 HYBRIS (null)+-169903959 in libminecraftpe.so+0x547b8a9 [0xf5df78a9]
#213 HYBRIS (null)+-169903959 in libminecraftpe.so+0x547b8a9 [0xf5df78a9]
#251 HYBRIS (null)+-143612856 in libminecraftpe.so+0x6d8e448 [0xf770a448]
#318 HYBRIS Core::Result::~Result()+9 in libminecraftpe.so+0x3cce349 [0xf464a349]
#326 HYBRIS (null)+-143612856 in libminecraftpe.so+0x6d8e448 [0xf770a448]
#420 HYBRIS (null)+-169740724 in libminecraftpe.so+0x54a364c [0xf5e1f64c]
#424 HYBRIS (null)+-169740724 in libminecraftpe.so+0x54a364c [0xf5e1f64c]
#431 HYBRIS operator new(unsigned int)+12 in libminecraftpe.so+0x542ac8c [0xf5da6c8c]
#480 HYBRIS (null)+-169878378 in libminecraftpe.so+0x5481c96 [0xf5dfdc96]
Aborted (core dumped)

**Comment by MCMrARM** [comment]
Yeah, unsupported at the moment.

**Comment by TheBrokenRail** [comment]
@MCMrARM When will this be fixed?

**Comment by ChristopherHX** [comment]
I fixed the crash before starting the Server 1.12,
~~Now crashes after / while shutdown~~ Resolved with last minecraft-symbols PR update
look at my PR for more Information https://github.com/minecraft-linux/mcpelauncher-server/pull/6
